name: Freeze 
author: Arjun Govindjee
description: Automatically whitelist any online users.
version: 0.2
main: com.carboncraft.Freeze.Freeze

commands:
  freeze:
    description: Add all online users to the whitelist.
    permission: freeze.freeze
    permission-message: ยง4You do not have permission to do that.
