name: Freeze 
author: Arjun Govindjee
description: Automatically whitelist any online users.
version: 0.24
main: com.carboncraft.freeze.Freeze

commands:
  freeze:
    description: Add all online users to the whitelist. For help type /freeze h
    usage: /freeze [arguments ...]
    permission: freeze.freeze
    permission-message: ยง4You do not have permission to do that.
